"""Write the new pdf_generator.py from a clean Python string."""
import pathlib

TARGET = pathlib.Path(__file__).parent.parent / "src" / "clinical" / "pdf_generator.py"

CODE = (
    '"""Generate a print-ready Vietnamese clinical summary PDF.\n'
    "\n"
    "Follows the standard Vietnamese Ban Tom Tat Benh An layout:\n"
    "  I.   Thong tin hanh chinh\n"
    "  II.  Chan doan & van de lam sang\n"
    "  III. Thuoc dieu tri\n"
    "  IV.  Ket qua can lam sang (trend + lan kham gan nhat)\n"
    "  V.   Diem can theo doi / Canh bao  (chi in neu co noi dung)\n"
    "\n"
    "Evidence citations remain available in the review application but are not printed.\n"
    '"""\n'
    "\n"
    "from __future__ import annotations\n"
    "\n"
    "import html\n"
    "import os\n"
    "import re\n"
    "from datetime import datetime\n"
    "from io import BytesIO\n"
    "from pathlib import Path\n"
    "\n"
    "from reportlab.lib import colors\n"
    "from reportlab.lib.enums import TA_LEFT\n"
    "from reportlab.lib.pagesizes import A4\n"
    "from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet\n"
    "from reportlab.lib.units import mm\n"
    "from reportlab.pdfbase import pdfmetrics\n"
    "from reportlab.pdfbase.ttfonts import TTFont\n"
    "from reportlab.platypus import (\n"
    "    HRFlowable,\n"
    "    KeepTogether,\n"
    "    Paragraph,\n"
    "    SimpleDocTemplate,\n"
    "    Spacer,\n"
    "    Table,\n"
    "    TableStyle,\n"
    ")\n"
    "\n"
    "from src.clinical.canonical import PatientSummary, ReviewResponse\n"
    "\n"
    "# --- Colour palette ---\n"
    'NAVY    = colors.HexColor("#172033")\n'
    'SLATE   = colors.HexColor("#334155")\n'
    'MUTED   = colors.HexColor("#64748B")\n'
    'LINE    = colors.HexColor("#CBD5E1")\n'
    'SURFACE = colors.HexColor("#F1F5F9")\n'
    'TEAL    = colors.HexColor("#0F766E")\n'
    'TEAL_LT = colors.HexColor("#CCFBF1")\n'
    'AMBER   = colors.HexColor("#B45309")\n'
    'AMBER_LT= colors.HexColor("#FFF7ED")\n'
    'RED     = colors.HexColor("#B42318")\n'
    'RED_LT  = colors.HexColor("#FEF3F2")\n'
    "WHITE   = colors.white\n"
    'BLACK   = colors.HexColor("#0F172A")\n'
    "\n"
    "PAGE_WIDTH, PAGE_HEIGHT = A4\n"
    "LM = 18 * mm\n"
    "RM = 18 * mm\n"
    "CW = PAGE_WIDTH - LM - RM\n"
    "\n"
    "\n"
    "def _font_candidates() -> list[dict[str, str]]:\n"
    '    configured = os.getenv("CLINICAL_PDF_FONT_DIR")\n'
    "    candidates: list[dict[str, str]] = []\n"
    "    if configured:\n"
    "        root = Path(configured)\n"
    "        candidates.append({\n"
    '            "regular": str(root / "DejaVuSans.ttf"),\n'
    '            "bold":    str(root / "DejaVuSans-Bold.ttf"),\n'
    '            "italic":  str(root / "DejaVuSans-Oblique.ttf"),\n'
    "        })\n"
    "    candidates.extend([\n"
    '        {"regular": "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",\n'
    '         "bold":    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",\n'
    '         "italic":  "/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf"},\n'
    '        {"regular": "/usr/share/fonts/dejavu/DejaVuSans.ttf",\n'
    '         "bold":    "/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf",\n'
    '         "italic":  "/usr/share/fonts/dejavu/DejaVuSans-Oblique.ttf"},\n'
    r'        {"regular": r"C:\Windows\Fonts\arial.ttf",' + "\n"
    r'         "bold":    r"C:\Windows\Fonts\arialbd.ttf",' + "\n"
    r'         "italic":  r"C:\Windows\Fonts\ariali.ttf"},' + "\n"
    r'        {"regular": r"C:\Windows\Fonts\DejaVuSans.ttf",' + "\n"
    r'         "bold":    r"C:\Windows\Fonts\DejaVuSans-Bold.ttf",' + "\n"
    r'         "italic":  r"C:\Windows\Fonts\DejaVuSans-Oblique.ttf"},' + "\n"
    "    ])\n"
    "    return candidates\n"
    "\n"
    "\n"
    "def _register_fonts() -> tuple[str, str, str]:\n"
    "    for c in _font_candidates():\n"
    '        reg = c.get("regular", "")\n'
    "        if not Path(reg).is_file():\n"
    "            continue\n"
    '        bold = c.get("bold", "")\n'
    "        bold_path = bold if Path(bold).is_file() else reg\n"
    '        italic = c.get("italic", "")\n'
    "        italic_path = italic if Path(italic).is_file() else reg\n"
    "        try:\n"
    '            pdfmetrics.registerFont(TTFont("CS", reg))\n'
    '            pdfmetrics.registerFont(TTFont("CS-B", bold_path))\n'
    '            pdfmetrics.registerFont(TTFont("CS-I", italic_path))\n'
    '            pdfmetrics.registerFontFamily("CS", normal="CS", bold="CS-B",\n'
    '                                          italic="CS-I", boldItalic="CS-B")\n'
    '            return "CS", "CS-B", "CS-I"\n'
    "        except Exception:\n"
    "            continue\n"
    '    return "Helvetica", "Helvetica-Bold", "Helvetica-Oblique"\n'
    "\n"
    "\n"
    "FONT, FONT_B, FONT_I = _register_fonts()\n"
    "\n"
    "\n"
    "def _safe(v: object | None) -> str:\n"
    "    if v is None:\n"
    '        return ""\n'
    '    return html.escape(str(v), quote=False).replace("\\n", "<br/>")\n'
    "\n"
    "\n"
    "def _fmt_date(v: str | None, *, time: bool = False) -> str:\n"
    "    if not v:\n"
    '        return "Chua ghi nhan"\n'
    "    raw = v.strip()\n"
    "    try:\n"
    '        dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))\n'
    '        return dt.strftime("%d/%m/%Y %H:%M") if time else dt.strftime("%d/%m/%Y")\n'
    "    except ValueError:\n"
    "        return raw\n"
    "\n"
    "\n"
    "_MED_REPL = {\n"
    '    " (Type 2 diabetes mellitus)": "",\n'
    '    " (Hypertension)": "",\n'
    '    " (Chronic kidney disease)": "",\n'
    '    "Type 2 diabetes mellitus": "Dai thao duong tip 2",\n'
    '    "Hypertension": "Tang huyet ap",\n'
    '    "Chronic kidney disease": "Benh than man",\n'
    '    "Status: finished": "Da hoan thanh",\n'
    '    "Status: active": "Dang duy tri",\n'
    '    "Status: completed": "Da ket thuc dot",\n'
    '    "status: active": "Dang duy tri",\n'
    '    "status: completed": "Da hoan thanh",\n'
    '    "type 2": "tip 2",\n'
    "}\n"
    "\n"
    "\n"
    "def _clean(text: str) -> str:\n"
    '    result = str(text or "").strip()\n'
    "    for src, tgt in _MED_REPL.items():\n"
    "        result = result.replace(src, tgt)\n"
    "    return result\n"
    "\n"
    "\n"
    "# --- Styles ---\n"
    "def _styles() -> dict[str, ParagraphStyle]:\n"
    "    base = getSampleStyleSheet()\n"
    "    return {\n"
    '        "doc_title": ParagraphStyle("DocTitle", parent=base["Normal"],\n'
    "            fontName=FONT_B, fontSize=16, leading=20,\n"
    "            textColor=NAVY, alignment=TA_LEFT, spaceAfter=1*mm),\n"
    '        "doc_sub": ParagraphStyle("DocSub", parent=base["Normal"],\n'
    "            fontName=FONT, fontSize=8.5, leading=12,\n"
    "            textColor=MUTED, spaceAfter=3*mm),\n"
    '        "lbl": ParagraphStyle("Lbl", parent=base["Normal"],\n'
    "            fontName=FONT_B, fontSize=7, leading=10, textColor=MUTED),\n"
    '        "val": ParagraphStyle("Val", parent=base["Normal"],\n'
    "            fontName=FONT, fontSize=8.8, leading=12, textColor=NAVY),\n"
    '        "val_b": ParagraphStyle("ValB", parent=base["Normal"],\n'
    "            fontName=FONT_B, fontSize=9, leading=12, textColor=NAVY),\n"
    '        "sec_hdr": ParagraphStyle("SecHdr", parent=base["Normal"],\n'
    "            fontName=FONT_B, fontSize=9, leading=12,\n"
    "            textColor=WHITE, alignment=TA_LEFT),\n"
    '        "body": ParagraphStyle("Body", parent=base["BodyText"],\n'
    "            fontName=FONT, fontSize=9.2, leading=14,\n"
    "            textColor=BLACK, leftIndent=5*mm, firstLineIndent=-4*mm,\n"
    "            spaceAfter=1.2*mm),\n"
    '        "note": ParagraphStyle("Note", parent=base["BodyText"],\n'
    "            fontName=FONT, fontSize=8.5, leading=13, textColor=SLATE),\n"
    '        "note_lbl": ParagraphStyle("NoteLbl", parent=base["BodyText"],\n'
    "            fontName=FONT_B, fontSize=8, leading=11,\n"
    "            textColor=TEAL, spaceAfter=1*mm),\n"
    '        "small": ParagraphStyle("Small", parent=base["Normal"],\n'
    "            fontName=FONT, fontSize=7.2, leading=10, textColor=MUTED),\n"
    '        "appr": ParagraphStyle("Appr", parent=base["Normal"],\n'
    "            fontName=FONT_B, fontSize=10, leading=13, textColor=TEAL),\n"
    '        "warn_lbl": ParagraphStyle("WarnLbl", parent=base["BodyText"],\n'
    "            fontName=FONT_B, fontSize=8, leading=11,\n"
    "            textColor=RED, spaceAfter=1*mm),\n"
    "    }\n"
    "\n"
    "\n"
    "# --- Page chrome ---\n"
    "def _chrome(canvas, doc) -> None:\n"
    "    canvas.saveState()\n"
    "    canvas.setFillColor(TEAL)\n"
    "    canvas.rect(0, PAGE_HEIGHT - 2.5*mm, PAGE_WIDTH, 2.5*mm, stroke=0, fill=1)\n"
    "    canvas.setFont(FONT_B, 7.8)\n"
    "    canvas.setFillColor(NAVY)\n"
    '    canvas.drawString(LM, PAGE_HEIGHT - 10*mm, "HO SO LAM SANG - TAI LIEU BAO MAT")\n'
    "    canvas.setFont(FONT, 7)\n"
    "    canvas.setFillColor(MUTED)\n"
    '    canvas.drawRightString(PAGE_WIDTH - RM, PAGE_HEIGHT - 10*mm, f"Trang {doc.page}")\n'
    "    canvas.setStrokeColor(LINE)\n"
    "    canvas.setLineWidth(0.5)\n"
    "    canvas.line(LM, PAGE_HEIGHT - 14*mm, PAGE_WIDTH - RM, PAGE_HEIGHT - 14*mm)\n"
    "    canvas.line(LM, 13*mm, PAGE_WIDTH - RM, 13*mm)\n"
    "    canvas.setFont(FONT_I, 6.8)\n"
    "    canvas.setFillColor(MUTED)\n"
    "    canvas.drawString(LM, 8*mm,\n"
    '        "Ban tom tat dieu tri duoc phe duyet - chi phuc vu ra soat lam sang")\n'
    "    canvas.restoreState()\n"
    "\n"
    "\n"
    "# --- Layout helpers ---\n"
    "def _info_grid(rows: list[list], styles: dict) -> Table:\n"
    "    col_w = [27*mm, CW/2 - 27*mm - 3*mm, 27*mm, CW/2 - 27*mm - 3*mm]\n"
    '    t = Table(rows, colWidths=col_w, hAlign="LEFT")\n'
    "    t.setStyle(TableStyle([\n"
    '        ("BACKGROUND", (0, 0), (-1, -1), SURFACE),\n'
    '        ("BOX",        (0, 0), (-1, -1), 0.6, LINE),\n'
    '        ("INNERGRID",  (0, 0), (-1, -1), 0.3, LINE),\n'
    '        ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),\n'
    '        ("LEFTPADDING",  (0, 0), (-1, -1), 5),\n'
    '        ("RIGHTPADDING", (0, 0), (-1, -1), 5),\n'
    '        ("TOPPADDING",   (0, 0), (-1, -1), 4),\n'
    '        ("BOTTOMPADDING",(0, 0), (-1, -1), 4),\n'
    "    ]))\n"
    "    return t\n"
    "\n"
    "\n"
    "def _sec_hdr(roman: str, title: str, styles: dict) -> Table:\n"
    "    t = Table(\n"
    '        [[Paragraph(roman, styles["sec_hdr"]),\n'
    "          Paragraph(_safe(title), ParagraphStyle(\n"
    '              "SecTl", parent=styles["sec_hdr"],\n'
    "              textColor=NAVY, fontName=FONT_B))]],\n"
    "        colWidths=[10*mm, CW - 10*mm], hAlign=\"LEFT\",\n"
    "    )\n"
    "    t.setStyle(TableStyle([\n"
    '        ("BACKGROUND", (0, 0), (0, 0), TEAL),\n'
    '        ("BACKGROUND", (1, 0), (1, 0), SURFACE),\n'
    '        ("BOX",  (0, 0), (-1, -1), 0.6, LINE),\n'
    '        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),\n'
    '        ("LEFTPADDING",  (0, 0), (0, 0), 3),\n'
    '        ("RIGHTPADDING", (0, 0), (0, 0), 3),\n'
    '        ("TOPPADDING",   (0, 0), (-1, -1), 5),\n'
    '        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),\n'
    '        ("LEFTPADDING",  (1, 0), (1, 0), 8),\n'
    "    ]))\n"
    "    return t\n"
    "\n"
    "\n"
    "def _notice_box(label: str, text: str, styles: dict,\n"
    "                bg=TEAL_LT, border_color=None,\n"
    '                label_style_key="note_lbl") -> Table:\n'
    "    if border_color is None:\n"
    '        border_color = colors.HexColor("#A7D9D2")\n'
    '    ls = ParagraphStyle(f"NB{abs(hash(label)) % 99999}", parent=styles[label_style_key])\n'
    "    t = Table(\n"
    "        [[Paragraph(_safe(label), ls)],\n"
    '         [Paragraph(_safe(text), styles["note"])]],\n'
    "        colWidths=[CW], hAlign=\"LEFT\",\n"
    "    )\n"
    "    t.setStyle(TableStyle([\n"
    '        ("BACKGROUND", (0, 0), (-1, -1), bg),\n'
    '        ("BOX",        (0, 0), (-1, -1), 0.7, border_color),\n'
    '        ("LEFTPADDING",  (0, 0), (-1, -1), 9),\n'
    '        ("RIGHTPADDING", (0, 0), (-1, -1), 9),\n'
    '        ("TOPPADDING",   (0, 0), (-1, -1), 6),\n'
    '        ("BOTTOMPADDING",(0, 0), (-1, -1), 6),\n'
    "    ]))\n"
    "    return t\n"
    "\n"
    "\n"
    "# --- Claim normalisation ---\n"
    "_FRAG_ONLY = re.compile(r'^\\d+(?:\\.\\d+)?\\s*(?:mg|g|ml|mcg|ui|iu)?$', re.IGNORECASE)\n"
    "_DATE_INL  = re.compile(r'\\s*ng[aA]y\\s+\\d{4}-\\d{2}-\\d{2}', re.IGNORECASE)\n"
    "_TREND_PFX = re.compile(r'^(?:Di[eE]n ti[eE]n|Dien tien)\\s+', re.IGNORECASE)\n"
    "\n"
    "_LOINC_DISP = {\n"
    '    "33914-3": "eGFR",\n'
    '    "8480-6": "Huyet ap tam thu",\n'
    '    "8462-4": "Huyet ap tam truong",\n'
    '    "1742-6": "ALT",\n'
    '    "13457-7": "LDL-C",\n'
    '    "718-7": "Hemoglobin",\n'
    '    "29463-7": "Can nang",\n'
    '    "8867-4": "Nhip tim",\n'
    '    "4548-4": "HbA1c",\n'
    '    "2339-0": "Duong huyet",\n'
    '    "2160-0": "Creatinine",\n'
    '    "glucose": "Duong huyet",\n'
    '    "duong huyet": "Duong huyet",\n'
    '    "hba1c": "HbA1c",\n'
    '    "creatinine": "Creatinine",\n'
    '    "egfr": "eGFR",\n'
    '    "ldl-c": "LDL-C",\n'
    '    "ldl": "LDL-C",\n'
    '    "alt": "ALT",\n'
    '    "hemoglobin": "Hemoglobin",\n'
    '    "huyet ap tam thu": "Huyet ap tam thu",\n'
    '    "huyet ap tam truong": "Huyet ap tam truong",\n'
    '    "nhip tim": "Nhip tim",\n'
    '    "can nang": "Can nang",\n'
    "}\n"
    "\n"
    "\n"
    "def _disp(raw: str) -> str:\n"
    "    k = raw.strip()\n"
    "    return _LOINC_DISP.get(k, _LOINC_DISP.get(k.lower(), k))\n"
    "\n"
    "\n"
    "def _strip_pfx(text: str) -> str:\n"
    "    t = text.strip()\n"
    "    pfxs = [\n"
    "        r'(?i)^thu[oO][cC](?:\\s+hi[eE]n\\s+t[aA]i)?:\\s*',\n"
    "        r'(?i)^ch[aA]n\\s+[dD][oO][aA]n/t[iI]nh\\s+tr[aA]ng\\s+b[eE]nh:\\s*',\n"
    "        r'(?i)^x[eE]t\\s+nghi[eE]m:\\s*',\n"
    "        r'(?i)^di[eE]n\\s+ti[eE]n\\s+',\n"
    "    ]\n"
    "    for p in pfxs:\n"
    "        t = re.sub(p, '', t).strip()\n"
    "    t = re.sub(\n"
    "        r'(?i)\\s*(?::\\s*tr[aA]ng\\s+th[aA]i:\\s*[dD][aA]ng\\s+s[uU]\\s+d[uU]ng'\n"
    "        r'|:\\s*[dD][aA]ng\\s+s[uU]\\s+d[uU]ng|\\([dD][aA]ng\\s+s[uU]\\s+d[uU]ng\\))',\n"
    "        '', t).strip()\n"
    "    return t\n"
    "\n"
    "\n"
    "def _is_frag(text: str) -> bool:\n"
    "    return bool(_FRAG_ONLY.match(text.strip()))\n"
    "\n"
    "\n"
    "def _fmt_trend(raw: str) -> str:\n"
    "    body = _TREND_PFX.sub('', raw.strip())\n"
    "    ci = body.find(':')\n"
    "    if ci > 0:\n"
    "        body = _disp(body[:ci].strip()) + body[ci:]\n"
    "    body = re.sub(r'(\\d+)\\.0(?=\\s|$|[^\\d])', r'\\1', body)\n"
    "    return body\n"
    "\n"
    "\n"
    "def _fmt_single(raw: str) -> str:\n"
    "    t = _strip_pfx(raw)\n"
    "    m = re.match(\n"
    "        r'(.+?)\\s+ng[aA]y\\s+(\\d{4}-\\d{2}-\\d{2})[:\\s]+k[eE]t\\s+qu[aA][:\\s]+(.+)',\n"
    "        t, re.IGNORECASE)\n"
    "    if m:\n"
    "        name  = _disp(m.group(1).strip())\n"
    "        value = m.group(3).strip()\n"
    "        try:\n"
    "            dt = datetime.strptime(m.group(2), '%Y-%m-%d')\n"
    "            ds = dt.strftime('%d/%m/%Y')\n"
    "        except ValueError:\n"
    "            ds = m.group(2)\n"
    "        return f\"{name}: {value}  <font color='#64748B'>({ds})</font>\"\n"
    "    return _clean(t)\n"
    "\n"
    "\n"
    "def _dkey_med(text: str) -> str:\n"
    "    t = text.lower()\n"
    "    t = re.sub(r'\\b\\d{4}-\\d{2}-\\d{2}\\b', '', t)\n"
    "    t = re.sub(r'(?:trang thai|ghi nhan|dang su dung|active|stopped|discontinued).*', '', t)\n"
    "    t = re.sub(r'\\(.*?\\)', '', t).strip()\n"
    "    m = re.search(r'^([a-z0-9 ]+?\\d+(?:\\.\\d+)?\\s*(?:mg|g|ml|mcg|ui|iu)?)', t)\n"
    "    return f\"med:{m.group(1).strip()}\" if m else f\"med:{t[:35]}\"\n"
    "\n"
    "\n"
    "def _dkey_lab(text: str, date: str) -> str:\n"
    "    wod = re.sub(r'\\b\\d{4}-\\d{2}-\\d{2}\\b', '', text.lower())\n"
    "    vm  = re.search(r'(?:ket qua|:)\\s*(\\d+(?:\\.\\d+)?)', wod)\n"
    "    val = re.sub(r'\\.0$', '', vm.group(1)) if vm else ''\n"
    "    for k, tk in [('hba1c','h1'), ('duong huyet','gl'), ('glucose','gl'),\n"
    "                  ('creatinine','cr'), ('egfr','egfr'), ('tam thu','bps'),\n"
    "                  ('tam truong','bpd'), (' alt','alt'), ('ldl','ldl'),\n"
    "                  ('hemoglobin','hgb'), ('nhip tim','hr'), ('can nang','wt')]:\n"
    "        if k in wod:\n"
    "            return f\"lab:{tk}:{date}:{val}\"\n"
    "    return f\"lab:{wod[:14].strip()}:{date}:{val}\"\n"
    "\n"
    "\n"
    "def _dkey_cond(text: str) -> str:\n"
    "    t = text.lower()\n"
    "    t = re.sub(r'\\(.*?\\)', '', t)\n"
    "    t = re.sub(r'(?:chan doan|diagnosis|condition)[^:]*:\\s*', '', t)\n"
    "    t = re.sub(r'ghi nhan\\s+\\d{4}-\\d{2}-\\d{2}', '', t).strip()\n"
    "    return f\"cond:{t}\"\n"
    "\n"
    "\n"
    "def _extract(section_code: str, claims_raw: list) -> list[tuple[str, str]]:\n"
    "    seen: set[str] = set()\n"
    "    result: list[tuple[str, str]] = []\n"
    "\n"
    "    if section_code == 'active_conditions':\n"
    "        for clm in claims_raw:\n"
    "            t = _clean(_strip_pfx(clm.text or ''))\n"
    "            if not t:\n"
    "                continue\n"
    "            k = _dkey_cond(t)\n"
    "            if k not in seen:\n"
    "                seen.add(k)\n"
    "                result.append((t, clm.status))\n"
    "\n"
    "    elif section_code == 'current_medications':\n"
    "        priority: dict[str, tuple[str, str]] = {}\n"
    "        for clm in claims_raw:\n"
    "            raw = clm.text or ''\n"
    "            fmt = _strip_pfx(raw)\n"
    "            if not fmt:\n"
    "                continue\n"
    "            fmt = _DATE_INL.sub('', fmt).strip()\n"
    "            fmt = _clean(fmt)\n"
    "            if not fmt or _is_frag(fmt):\n"
    "                continue\n"
    "            k = _dkey_med(fmt)\n"
    "            has_dose = bool(re.search(r'\\d+\\s*(?:mg|g|ml|mcg)', fmt, re.IGNORECASE))\n"
    "            is_old = bool(re.search(r'hoan thanh|completed|stopped|discontinued', raw, re.IGNORECASE))\n"
    "            if k not in priority:\n"
    "                priority[k] = (fmt, clm.status)\n"
    "            else:\n"
    "                existing, _ = priority[k]\n"
    "                ex_has_dose = bool(re.search(r'\\d+\\s*(?:mg|g|ml|mcg)', existing, re.IGNORECASE))\n"
    "                if has_dose and not ex_has_dose and not is_old:\n"
    "                    priority[k] = (fmt, clm.status)\n"
    "        bare_names: set[str] = set()\n"
    "        for k, (fmt, _) in priority.items():\n"
    "            bm = re.match(r'^([a-zA-Z0-9 ]+?)(?:\\s+\\d)', fmt, re.IGNORECASE)\n"
    "            if bm:\n"
    "                bare_names.add(bm.group(1).strip().lower())\n"
    "        for k, (fmt, status) in priority.items():\n"
    "            has_dose = bool(re.search(r'\\d+\\s*(?:mg|g|ml|mcg)', fmt, re.IGNORECASE))\n"
    "            if not has_dose and fmt.strip().lower() in bare_names:\n"
    "                continue\n"
    "            is_old = bool(re.search(r'hoan thanh|completed|stopped|discontinued', fmt, re.IGNORECASE))\n"
    "            if is_old:\n"
    "                dm = re.match(r'^([a-zA-Z0-9]+)', fmt)\n"
    "                if dm:\n"
    "                    base = dm.group(1).lower()\n"
    "                    if any(base in f.lower() and 'hoan thanh' not in f.lower()\n"
    "                           for f, _ in result):\n"
    "                        continue\n"
    "            if k not in seen:\n"
    "                seen.add(k)\n"
    "                result.append((fmt, status))\n"
    "\n"
    "    elif section_code == 'recent_results':\n"
    "        trends: dict[str, tuple[str, str]] = {}\n"
    "        singles: dict[str, tuple[str, str]] = {}\n"
    "        for clm in claims_raw:\n"
    "            raw   = clm.text or ''\n"
    "            raw_l = raw.lower()\n"
    "            dm = re.search(r'\\b(\\d{4}-\\d{2}-\\d{2})\\b', raw)\n"
    "            date_key = dm.group(1) if dm else 'no_date'\n"
    "            is_trend  = 'dien tien' in raw_l or 'trend' in raw_l\n"
    "            is_single = (re.search(r'ng[aA]y\\s+\\d{4}-\\d{2}-\\d{2}', raw, re.IGNORECASE)\n"
    "                         and 'ket qua' in raw_l)\n"
    "            if is_trend:\n"
    "                body = _TREND_PFX.sub('', raw.strip())\n"
    "                ci = body.find(':')\n"
    "                mkey = _disp(body[:ci].strip()) if ci > 0 else body[:20]\n"
    "                if mkey not in trends:\n"
    "                    trends[mkey] = (_fmt_trend(raw), clm.status)\n"
    "            elif is_single:\n"
    "                lk = _dkey_lab(raw_l, date_key)\n"
    "                if lk not in singles:\n"
    "                    singles[lk] = (_fmt_single(raw), clm.status)\n"
    "        latest = ''\n"
    "        for lk in singles:\n"
    "            parts = lk.split(':')\n"
    "            if len(parts) >= 3 and parts[2] > latest:\n"
    "                latest = parts[2]\n"
    "        for mk, (text, status) in trends.items():\n"
    "            result.append((text, status))\n"
    "        for lk, (text, status) in singles.items():\n"
    "            parts = lk.split(':')\n"
    "            d = parts[2] if len(parts) >= 3 else ''\n"
    "            if d != latest:\n"
    "                continue\n"
    "            tl = text.lower()\n"
    "            covered = any(mk.lower() in tl for mk in trends)\n"
    "            if not covered and lk not in seen:\n"
    "                seen.add(lk)\n"
    "                result.append((text, status))\n"
    "\n"
    "    else:\n"
    "        for clm in claims_raw:\n"
    "            t = _clean(_strip_pfx(clm.text or ''))\n"
    "            if not t:\n"
    "                continue\n"
    "            k = re.sub(r'\\s+', ' ', t.lower().strip())\n"
    "            if k not in seen:\n"
    "                seen.add(k)\n"
    "                result.append((t, clm.status))\n"
    "\n"
    "    return result\n"
    "\n"
    "\n"
    "# --- Section metadata ---\n"
    "_ROMAN = ['I', 'II', 'III', 'IV', 'V', 'VI']\n"
    "_SEC_META: dict[str, tuple[str, str]] = {\n"
    "    'active_conditions':   ('CHAN DOAN VA VAN DE LAM SANG',\n"
    "                            'Cac benh ly dang duoc theo doi va dieu tri'),\n"
    "    'current_medications': ('THUOC VA PHAC DO DIEU TRI',\n"
    "                            'Danh muc thuoc hien tai duoc ke don'),\n"
    "    'recent_results':      ('KET QUA CAN LAM SANG',\n"
    "                            'Dien tien cac chi so va ket qua lan kham gan nhat'),\n"
    "    'changes_to_review':   ('DIEM CAN THEO DOI VA XEM XET',\n"
    "                            'Thay doi hoac mau thuan du lieu can bac si xac nhan'),\n"
    "    'data_gaps':           ('THONG TIN CAN BO SUNG',\n"
    "                            'Cac truong du lieu con thieu hoac can cap nhat'),\n"
    "}\n"
    "_MANDATORY = {'active_conditions', 'current_medications', 'recent_results'}\n"
    "_ORDER = [\n"
    "    'active_conditions', 'current_medications', 'recent_results',\n"
    "    'changes_to_review', 'data_gaps',\n"
    "]\n"
    "\n"
    "\n"
    "def generate_review_pdf(review: ReviewResponse, patient: PatientSummary | None = None) -> bytes:\n"
    '    """Return an A4 PDF following the standard Vietnamese Benh An summary format."""\n'
    "    buf = BytesIO()\n"
    "    doc = SimpleDocTemplate(\n"
    "        buf, pagesize=A4,\n"
    "        leftMargin=LM, rightMargin=RM,\n"
    "        topMargin=20*mm, bottomMargin=18*mm,\n"
    "        title=f'Ban tom tat benh an - {review.patient_id}',\n"
    "        author='Clinical Review Copilot',\n"
    "        subject='Ban tom tat dieu tri da duoc bac si phe duyet',\n"
    "    )\n"
    "    S = _styles()\n"
    "    story: list = []\n"
    "\n"
    "    # --- Header block ---\n"
    "    story.append(Paragraph('BAN TOM TAT BENH AN', S['doc_title']))\n"
    "    story.append(Paragraph(\n"
    "        'Phieu tong hop lam sang - da duoc bac si kiem tra va phe duyet',\n"
    "        S['doc_sub']))\n"
    "\n"
    "    pname  = patient.pseudonym if patient else review.patient_id\n"
    "    page   = f'{patient.age} tuoi' if patient and patient.age is not None else '--'\n"
    "    sex_map = {'male': 'Nam', 'female': 'Nu', 'other': 'Khac'}\n"
    "    psex   = sex_map.get(patient.sex, '--') if patient else '--'\n"
    "    pcond  = _clean((patient.primary_condition if patient else None) or '--')\n"
    "    cov_s  = _fmt_date(review.coverage.start_date)\n"
    "    cov_e  = _fmt_date(review.coverage.end_date)\n"
    "    appr_d = _fmt_date(review.approved_at or review.updated_at)\n"
    "    lbl, val, val_b = S['lbl'], S['val'], S['val_b']\n"
    "\n"
    "    story.append(_info_grid([\n"
    "        [Paragraph('HO VA TEN', lbl), Paragraph(_safe(pname), val_b),\n"
    "         Paragraph('MA BENH NHAN', lbl), Paragraph(_safe(review.patient_id), val_b)],\n"
    "        [Paragraph('TUOI', lbl), Paragraph(_safe(page), val),\n"
    "         Paragraph('GIOI TINH', lbl), Paragraph(_safe(psex), val)],\n"
    "        [Paragraph('CHAN DOAN CHINH', lbl), Paragraph(_safe(pcond), val),\n"
    "         Paragraph('TRANG THAI HO SO', lbl),\n"
    "         Paragraph(\"<font color='#0F766E'><b>DA PHE DUYET</b></font>\", val)],\n"
    "        [Paragraph('KHOANG DU LIEU', lbl),\n"
    "         Paragraph(f'{_safe(cov_s)} -- {_safe(cov_e)}', val),\n"
    "         Paragraph('NGAY PHE DUYET', lbl), Paragraph(_safe(appr_d), val)],\n"
    "        [Paragraph('PHIEN BAN', lbl),\n"
    "         Paragraph(f\"v{review.version}  <font color='#64748B'>{_safe(review.review_version_id)}</font>\", val),\n"
    "         Paragraph('SO LUOT KHAM', lbl), Paragraph(str(review.coverage.encounter_count), val)],\n"
    "    ], S))\n"
    "    story.append(Spacer(1, 5*mm))\n"
    "\n"
    "    # --- Build section lookup ---\n"
    "    sec_lookup: dict[str, list] = {}\n"
    "    for sec in (review.sections or []):\n"
    "        sec_lookup.setdefault(sec.section_code, []).extend(sec.claims or [])\n"
    "    cli_notes: dict[str, str | None] = {\n"
    "        sec.section_code: sec.clinician_text for sec in (review.sections or [])\n"
    "    }\n"
    "\n"
    "    sn = 0\n"
    "    for scode in _ORDER:\n"
    "        raw_claims = sec_lookup.get(scode, [])\n"
    "        items = _extract(scode, raw_claims)\n"
    "        if not items and scode not in _MANDATORY:\n"
    "            continue\n"
    "        sn += 1\n"
    "        roman = _ROMAN[sn - 1] if sn <= len(_ROMAN) else str(sn)\n"
    "        title, subtitle = _SEC_META.get(scode, (scode.upper(), ''))\n"
    "\n"
    "        opening: list = [_sec_hdr(roman, title, S), Spacer(1, 1*mm)]\n"
    "        if subtitle:\n"
    "            opening.append(Paragraph(_safe(subtitle), S['small']))\n"
    "            opening.append(Spacer(1, 1.5*mm))\n"
    "        note_text = cli_notes.get(scode) or ''\n"
    "        if note_text.strip():\n"
    "            opening.extend([_notice_box('Ghi chu cua bac si', note_text.strip(), S), Spacer(1, 2*mm)])\n"
    "\n"
    "        if items:\n"
    "            ft, fs = items[0]\n"
    "            tag = \" <font color='#B45309'><b>[Can kiem tra]</b></font>\" if fs != 'verified' else ''\n"
    "            opening.append(Paragraph(f'* {_safe(ft)}{tag}', S['body']))\n"
    "            story.append(KeepTogether(opening))\n"
    "            for ct, cs in items[1:]:\n"
    "                tg = \" <font color='#B45309'><b>[Can kiem tra]</b></font>\" if cs != 'verified' else ''\n"
    "                story.append(Paragraph(f'* {_safe(ct)}{tg}', S['body']))\n"
    "        else:\n"
    "            opening.append(Paragraph('<i>Chua ghi nhan thong tin trong muc nay.</i>', S['note']))\n"
    "            story.append(KeepTogether(opening))\n"
    "        story.append(Spacer(1, 4*mm))\n"
    "\n"
    "    # --- Drug interactions / conflicts ---\n"
    "    sev = {'low': 'thap', 'moderate': 'trung binh', 'high': 'cao', 'unknown': 'chua xac dinh'}\n"
    "    warns = [\n"
    "        f\"Tuong tac thuoc ({sev.get(i.severity, i.severity)}): {i.description}\"\n"
    "        for i in review.drug_interactions\n"
    "        if i.status not in {'not_applicable', 'superseded'}\n"
    "    ] + [\n"
    "        f\"Mau thuan du lieu: {c.description}\" + (' (da xu ly)' if c.status == 'resolved' else '')\n"
    "        for c in review.conflicts\n"
    "    ]\n"
    "    if warns:\n"
    "        wt = '<br/>'.join(_safe(w) for w in warns)\n"
    "        sn += 1\n"
    "        roman = _ROMAN[sn - 1] if sn <= len(_ROMAN) else str(sn)\n"
    "        story.append(KeepTogether([\n"
    "            _sec_hdr(roman, 'CANH BAO LAM SANG', S), Spacer(1, 2*mm),\n"
    "            _notice_box('Canh bao va diem can luu y', wt, S,\n"
    "                        bg=RED_LT, border_color=colors.HexColor('#FDA29B'),\n"
    "                        label_style_key='warn_lbl'),\n"
    "            Spacer(1, 4*mm),\n"
    "        ]))\n"
    "\n"
    "    # --- Data quality flags ---\n"
    "    quality = [i.message for i in review.data_quality_flags\n"
    "               if i.status not in {'verified', 'dismissed'}]\n"
    "    if quality:\n"
    "        qt = '<br/>'.join(f'* {_safe(q)}' for q in quality)\n"
    "        story.extend([\n"
    "            _notice_box('Thong tin can kiem tra them', qt, S,\n"
    "                        bg=AMBER_LT, border_color=colors.HexColor('#FED7AA'),\n"
    "                        label_style_key='note_lbl'),\n"
    "            Spacer(1, 4*mm),\n"
    "        ])\n"
    "\n"
    "    # --- Approval block ---\n"
    "    appr_time = _fmt_date(review.approved_at or review.updated_at, time=True)\n"
    "    story.append(HRFlowable(width=CW, thickness=0.5, color=LINE))\n"
    "    story.append(Spacer(1, 3*mm))\n"
    "    abox = Table([\n"
    "        [Paragraph('DA PHE DUYET BOI BAC SI LAM SANG', S['appr'])],\n"
    "        [Paragraph(\n"
    "            'Bac si xac nhan da kiem tra noi dung tom tat va chiu trach nhiem chuyen mon.',\n"
    "            S['note'])],\n"
    "        [Paragraph(\n"
    "            f\"Thoi gian phe duyet: <b>{_safe(appr_time)}</b>  |  Ma phien ban: {_safe(review.review_version_id)}\",\n"
    "            S['small'])],\n"
    "    ], colWidths=[CW], hAlign='LEFT')\n"
    "    abox.setStyle(TableStyle([\n"
    "        ('BACKGROUND',   (0, 0), (-1, -1), TEAL_LT),\n"
    "        ('BOX',          (0, 0), (-1, -1), 0.9, colors.HexColor('#7DD3C7')),\n"
    "        ('LINEBEFORE',   (0, 0), (0, -1), 3, TEAL),\n"
    "        ('LEFTPADDING',  (0, 0), (-1, -1), 10),\n"
    "        ('RIGHTPADDING', (0, 0), (-1, -1), 10),\n"
    "        ('TOPPADDING',   (0, 0), (-1, -1), 6),\n"
    "        ('BOTTOMPADDING',(0, 0), (-1, -1), 6),\n"
    "    ]))\n"
    "    story.append(KeepTogether([abox]))\n"
    "    story.append(Spacer(1, 2*mm))\n"
    "    story.append(Paragraph(\n"
    "        _safe(review.disclaimer or\n"
    "              'Tai lieu phuc vu theo doi va dieu tri lam sang. '\n"
    "              'Bac si chiu trach nhiem cho moi quyet dinh chuyen mon.'),\n"
    "        S['small']))\n"
    "\n"
    "    doc.build(story, onFirstPage=_chrome, onLaterPages=_chrome)\n"
    "    content = buf.getvalue()\n"
    "    buf.close()\n"
    "    return content\n"
)

TARGET.write_text(CODE, encoding="utf-8")
print(f"Written {len(CODE)} chars to {TARGET}")
